[build]
  command = "npm install"
  publish = "."  # Deploys the whole backend

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
